<?php

namespace Database\Seeders;

use App\Models\Chambre;
use App\Models\Hotel;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        Hotel::query()
            ->where('nom', 'HotelEase Demo Hotel')
            ->orWhere('nom', 'Demo Hotel')
            ->orWhere('etoiles', '>', 5)
            ->delete();

        $hotels = [
            [
                'nom' => 'The Ritz London',
                'ville' => ['fr' => 'Londres', 'en' => 'London', 'ar' => 'لندن'],
                'pays' => 'Royaume-Uni',
                'adresse' => '150 Piccadilly, Londres',
                'etoiles' => 5,
                'prix_par_nuit' => 1100,
                'description' => [
                    'fr' => 'Palace emblématique de Londres',
                    'en' => 'London\'s most iconic luxury palace hotel',
                    'ar' => 'فندق القصر الأيقوني في لندن',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                'latitude' => 51.5074,
                'longitude' => -0.1419,
                'note_moyenne' => 4.8,
            ],
            [
                'nom' => 'Burj Al Arab',
                'ville' => ['fr' => 'Dubaï', 'en' => 'Dubai', 'ar' => 'دبي'],
                'pays' => 'Émirats Arabes Unis',
                'adresse' => 'Jumeirah St, Dubaï',
                'etoiles' => 5,
                'prix_par_nuit' => 1600,
                'description' => [
                    'fr' => 'Symbole du luxe absolu, suites panoramiques',
                    'en' => 'Symbol of absolute luxury with panoramic suites',
                    'ar' => 'رمز الفخامة المطلقة بأجنحة بانورامية',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'latitude' => 25.1412,
                'longitude' => 55.1853,
                'note_moyenne' => 4.9,
            ],
            [
                'nom' => 'Hôtel Plaza Athénée',
                'ville' => ['fr' => 'Paris', 'en' => 'Paris', 'ar' => 'باريس'],
                'pays' => 'France',
                'adresse' => '25 Avenue Montaigne, Paris',
                'etoiles' => 5,
                'prix_par_nuit' => 1250,
                'description' => [
                    'fr' => 'Palace mythique sur l\'avenue Montaigne',
                    'en' => 'Mythical palace on the prestigious Avenue Montaigne',
                    'ar' => 'قصر أسطوري على شارع مونتين الراقي',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
                'latitude' => 48.8661,
                'longitude' => 2.3048,
                'note_moyenne' => 4.8,
            ],
            [
                'nom' => 'Hotel Negresco',
                'ville' => ['fr' => 'Nice', 'en' => 'Nice', 'ar' => 'نيس'],
                'pays' => 'France',
                'adresse' => '37 Promenade des Anglais, Nice',
                'etoiles' => 5,
                'prix_par_nuit' => 640,
                'description' => [
                    'fr' => 'Palace emblématique sur la Promenade des Anglais',
                    'en' => 'Iconic palace on the famous Promenade des Anglais',
                    'ar' => 'قصر أيقوني على كورنيش البحر الشهير',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                'latitude' => 43.695,
                'longitude' => 7.265,
                'note_moyenne' => 4.6,
            ],
            [
                'nom' => 'Le Meurice',
                'ville' => ['fr' => 'Paris', 'en' => 'Paris', 'ar' => 'باريس'],
                'pays' => 'France',
                'adresse' => '228 Rue de Rivoli, Paris',
                'etoiles' => 5,
                'prix_par_nuit' => 750,
                'description' => [
                    'fr' => 'Palace mythique face aux jardins des Tuileries',
                    'en' => 'Mythical palace facing the Tuileries Gardens',
                    'ar' => 'قصر أسطوري يطل على حدائق التويلري',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                'latitude' => 48.8656,
                'longitude' => 2.3284,
                'note_moyenne' => 4.7,
            ],
            [
                'nom' => 'Shangri-La Paris',
                'ville' => ['fr' => 'Paris', 'en' => 'Paris', 'ar' => 'باريس'],
                'pays' => 'France',
                'adresse' => '10 Avenue d\'Iéna, Paris',
                'etoiles' => 5,
                'prix_par_nuit' => 890,
                'description' => [
                    'fr' => 'Vue imprenable sur la Tour Eiffel',
                    'en' => 'Breathtaking views of the Eiffel Tower',
                    'ar' => 'إطلالة خلابة على برج إيفل الشهير',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
                'latitude' => 48.8627,
                'longitude' => 2.2925,
                'note_moyenne' => 4.7,
            ],
            [
                'nom' => 'Atlantis The Palm',
                'ville' => ['fr' => 'Dubaï', 'en' => 'Dubai', 'ar' => 'دبي'],
                'pays' => 'Émirats Arabes Unis',
                'adresse' => 'Palm Jumeirah, Dubaï',
                'etoiles' => 5,
                'prix_par_nuit' => 620,
                'description' => [
                    'fr' => 'Resort iconique sur la Palm Jumeirah',
                    'en' => 'Iconic resort on the Palm Jumeirah island',
                    'ar' => 'منتجع أيقوني على جزيرة نخلة جميرا',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'latitude' => 25.1304,
                'longitude' => 55.1171,
                'note_moyenne' => 4.6,
            ],
            [
                'nom' => 'Armani Hotel Dubai',
                'ville' => ['fr' => 'Dubaï', 'en' => 'Dubai', 'ar' => 'دبي'],
                'pays' => 'Émirats Arabes Unis',
                'adresse' => 'Burj Khalifa, Dubaï',
                'etoiles' => 5,
                'prix_par_nuit' => 950,
                'description' => [
                    'fr' => 'Luxe absolu au cœur du Burj Khalifa',
                    'en' => 'Absolute luxury in the heart of Burj Khalifa',
                    'ar' => 'فخامة مطلقة في قلب برج خليفة',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
                'latitude' => 25.1972,
                'longitude' => 55.2744,
                'note_moyenne' => 4.7,
            ],
            [
                'nom' => 'Claridge\'s',
                'ville' => ['fr' => 'Londres', 'en' => 'London', 'ar' => 'لندن'],
                'pays' => 'Royaume-Uni',
                'adresse' => 'Brook Street, Mayfair, Londres',
                'etoiles' => 5,
                'prix_par_nuit' => 680,
                'description' => [
                    'fr' => 'Art déco emblématique au cœur de Mayfair',
                    'en' => 'Iconic Art Deco hotel in the heart of Mayfair',
                    'ar' => 'فندق آرت ديكو الأيقوني في قلب مايفير',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
                'latitude' => 51.5126,
                'longitude' => -0.1477,
                'note_moyenne' => 4.6,
            ],
            [
                'nom' => 'The Savoy',
                'ville' => ['fr' => 'Londres', 'en' => 'London', 'ar' => 'لندن'],
                'pays' => 'Royaume-Uni',
                'adresse' => 'Strand, Londres',
                'etoiles' => 5,
                'prix_par_nuit' => 720,
                'description' => [
                    'fr' => 'Légende de l\'hôtellerie britannique depuis 1889',
                    'en' => 'A legend of British hospitality since 1889',
                    'ar' => 'أسطورة الضيافة البريطانية منذ عام 1889',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800',
                'latitude' => 51.5101,
                'longitude' => -0.1202,
                'note_moyenne' => 4.7,
            ],
            [
                'nom' => 'Royal Mansour',
                'ville' => ['fr' => 'Marrakech', 'en' => 'Marrakech', 'ar' => 'مراكش'],
                'pays' => 'Maroc',
                'adresse' => 'Rue Abou Abbas El Sebti, Marrakech',
                'etoiles' => 5,
                'prix_par_nuit' => 1200,
                'description' => [
                    'fr' => 'Palais privé au cœur de la médina',
                    'en' => 'A private palace in the heart of the medina',
                    'ar' => 'قصر خاص في قلب المدينة العتيقة',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
                'latitude' => 31.6295,
                'longitude' => -7.9997,
                'note_moyenne' => 4.9,
            ],
            [
                'nom' => 'La Mamounia',
                'ville' => ['fr' => 'Marrakech', 'en' => 'Marrakech', 'ar' => 'مراكش'],
                'pays' => 'Maroc',
                'adresse' => 'Avenue Bab Jdid, Marrakech',
                'etoiles' => 5,
                'prix_par_nuit' => 850,
                'description' => [
                    'fr' => 'Palace légendaire aux jardins andalous',
                    'en' => 'Legendary palace with Andalusian gardens',
                    'ar' => 'قصر أسطوري بحدائق أندلسية خلابة',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi'],
                'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                'latitude' => 31.6217,
                'longitude' => -7.9899,
                'note_moyenne' => 4.8,
            ],
            [
                'nom' => 'Hotel de Russie',
                'ville' => ['fr' => 'Rome', 'en' => 'Rome', 'ar' => 'روما'],
                'pays' => 'Italie',
                'adresse' => 'Via del Babuino 9, Rome',
                'etoiles' => 5,
                'prix_par_nuit' => 580,
                'description' => [
                    'fr' => 'Oasis de luxe entre la Piazza del Popolo et la Via Veneto',
                    'en' => 'Luxury oasis between Piazza del Popolo and Via Veneto',
                    'ar' => 'واحة فاخرة بين بياتسا ديل بوبولو وفيا فينيتو',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'piscine'],
                'image' => 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800',
                'latitude' => 41.9105,
                'longitude' => 12.4768,
                'note_moyenne' => 4.6,
            ],
            [
                'nom' => 'Hotel Arts Barcelona',
                'ville' => ['fr' => 'Barcelone', 'en' => 'Barcelona', 'ar' => 'برشلونة'],
                'pays' => 'Espagne',
                'adresse' => 'Carrer de la Marina 19, Barcelone',
                'etoiles' => 5,
                'prix_par_nuit' => 490,
                'description' => [
                    'fr' => 'Gratte-ciel contemporain face à la mer Méditerranée',
                    'en' => 'Contemporary skyscraper facing the Mediterranean Sea',
                    'ar' => 'ناطحة سحاب معاصرة تطل على البحر الأبيض المتوسط',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                'latitude' => 41.3869,
                'longitude' => 2.1965,
                'note_moyenne' => 4.5,
            ],
            [
                'nom' => 'Four Seasons Maldives',
                'ville' => ['fr' => 'Malé', 'en' => 'Malé', 'ar' => 'ماليه'],
                'pays' => 'Maldives',
                'adresse' => 'Kuda Huraa, Maldives',
                'etoiles' => 5,
                'prix_par_nuit' => 2100,
                'description' => [
                    'fr' => 'Villas sur pilotis au-dessus du lagon turquoise',
                    'en' => 'Overwater villas above a turquoise lagoon',
                    'ar' => 'فيلات فوق الماء فوق بحيرة فيروزية رائعة',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi'],
                'image' => 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
                'latitude' => 4.3091,
                'longitude' => 73.466,
                'note_moyenne' => 4.9,
            ],
            [
                'nom' => 'The Plaza Hotel',
                'ville' => ['fr' => 'New York', 'en' => 'New York', 'ar' => 'نيويورك'],
                'pays' => 'États-Unis',
                'adresse' => '768 Fifth Avenue, New York',
                'etoiles' => 5,
                'prix_par_nuit' => 795,
                'description' => [
                    'fr' => 'Icône new-yorkaise face à Central Park',
                    'en' => 'New York icon facing Central Park',
                    'ar' => 'أيقونة نيويورك المطلة على سنترال بارك',
                ],
                'services' => ['spa', 'restaurant', 'wifi', 'parking'],
                'image' => 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
                'latitude' => 40.7644,
                'longitude' => -73.9748,
                'note_moyenne' => 4.7,
            ],
            [
                'nom' => 'Park Hyatt Tokyo',
                'ville' => ['fr' => 'Tokyo', 'en' => 'Tokyo', 'ar' => 'طوكيو'],
                'pays' => 'Japon',
                'adresse' => '3-7-1-2 Nishi-Shinjuku, Tokyo',
                'etoiles' => 5,
                'prix_par_nuit' => 650,
                'description' => [
                    'fr' => 'Vue panoramique sur Tokyo et le Mont Fuji',
                    'en' => 'Panoramic views of Tokyo and Mount Fuji',
                    'ar' => 'إطلالة بانورامية على طوكيو وجبل فوجي',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi'],
                'image' => 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
                'latitude' => 35.685,
                'longitude' => 139.694,
                'note_moyenne' => 4.8,
            ],
            [
                'nom' => 'Canaves Oia Suites',
                'ville' => ['fr' => 'Santorin', 'en' => 'Santorini', 'ar' => 'سانتوريني'],
                'pays' => 'Grèce',
                'adresse' => 'Oia, Santorin',
                'etoiles' => 5,
                'prix_par_nuit' => 980,
                'description' => [
                    'fr' => 'Suites creusées dans la caldeira avec vue mer infinie',
                    'en' => 'Suites carved into the caldera with endless sea views',
                    'ar' => 'أجنحة منحوتة في الجرف البركاني بإطلالة بحرية لا نهاية لها',
                ],
                'services' => ['spa', 'piscine', 'restaurant', 'wifi'],
                'image' => 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
                'latitude' => 36.4618,
                'longitude' => 25.3753,
                'note_moyenne' => 4.8,
            ],
            [
                'nom' => 'La Maison Blanche',
                'ville' => ['fr' => 'Tunis', 'en' => 'Tunis', 'ar' => 'تونس'],
                'pays' => 'Tunisie',
                'adresse' => 'Avenue Mohamed V, Tunis',
                'etoiles' => 4,
                'prix_par_nuit' => 180,
                'description' => [
                    'fr' => 'Élégance méditerranéenne au cœur de la capitale',
                    'en' => 'Mediterranean elegance in the heart of the capital',
                    'ar' => 'أناقة متوسطية في قلب العاصمة التونسية',
                ],
                'services' => ['restaurant', 'wifi', 'parking', 'climatisation'],
                'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                'latitude' => 36.8065,
                'longitude' => 10.1815,
                'note_moyenne' => 4.3,
            ],
        ];

        foreach ($hotels as $item) {
            $hotel = Hotel::query()->updateOrCreate(
                ['nom' => $item['nom']],
                [
                    'description' => $item['description'],
                    'adresse' => $item['adresse'],
                    'ville' => $item['ville'],
                    'latitude' => $item['latitude'],
                    'longitude' => $item['longitude'],
                    'etoiles' => $item['etoiles'],
                    'photos' => [$item['image']],
                    'noteMoyenne' => $item['note_moyenne'],
                    'services' => $item['services'],
                    'equipements' => $item['services'],
                    'estActif' => true,
                ]
            );

            Chambre::query()->updateOrCreate(
                [
                    'hotelId' => (string) $hotel->_id,
                    'nom' => 'Chambre Deluxe',
                ],
                [
                    'type' => 'DOUBLE',
                    'description' => 'Chambre premium avec prestations haut de gamme.',
                    'prix_base' => (float) $item['prix_par_nuit'],
                    'maxVoyageurs' => 2,
                    'equipements' => ['wifi', 'climatisation', 'tv'],
                    'photos' => [$item['image']],
                    'estDisponible' => true,
                    'etage' => 1,
                ]
            );
        }
    }
}
