@startuml
left to right direction
skinparam packageStyle rectangle

actor Administrateur as Admin

rectangle "HotelEase - Espace Admin" {
  usecase "Se connecter" as A0
  usecase "Gerer hotels" as A1
  usecase "Activer/Desactiver hotel" as A2
  usecase "Gerer chambres" as A3
  usecase "Gerer services" as A4
  usecase "Gerer utilisateurs" as A5
  usecase "Consulter stats globales" as A6
  usecase "Consulter paiements" as A7
  usecase "Exporter paiements CSV" as A8
}

Admin --> A0
Admin --> A1
Admin --> A2
Admin --> A3
Admin --> A4
Admin --> A5
Admin --> A6
Admin --> A7
Admin --> A8

A1 ..> A0 : <<include>>
A2 ..> A0 : <<include>>
A3 ..> A0 : <<include>>
A4 ..> A0 : <<include>>
A5 ..> A0 : <<include>>
A6 ..> A0 : <<include>>
A7 ..> A0 : <<include>>
A8 ..> A0 : <<include>>

A2 ..> A1 : <<extend>>
A8 ..> A7 : <<extend>>
@enduml
