@startuml
left to right direction
skinparam shadowing false
skinparam actorStyle awesome

actor "Administrateur" as Admin

rectangle "Gestion Administrative et Système" {
    (Gérer les hôtels) as UC_H
    (Modifier statut de disponibilité) as UC_T
    (Gérer les chambres) as UC_C
    (Gérer les services) as UC_S
    
    (Gérer les utilisateurs) as UC_U
    
    (Consulter les paiements) as UC_P
    (Exporter paiements CSV) as UC_CSV
    (Consulter stats globales) as UC_Stats

    ' Extensions logiques
    UC_T .> UC_H : <<extend>>
    UC_CSV .> UC_P : <<extend>>

    ' Liaisons principales
    Admin --> UC_H
    Admin --> UC_C
    Admin --> UC_S
    Admin --> UC_U
    Admin --> UC_P
    Admin --> UC_Stats
}
@enduml