@startuml
left to right direction
skinparam packageStyle rectangle

actor "Responsable Marketing" as Marketing

rectangle "HotelEase - Espace Marketing" {
  usecase "Se connecter" as M0
  usecase "Gerer promotions" as M1
  usecase "Consulter statistiques marketing" as M2
  usecase "Moderer avis" as M3
  usecase "Approuver avis" as M4
  usecase "Rejeter avis" as M5
  usecase "Repondre aux avis" as M6
  usecase "Exporter avis CSV" as M7
  usecase "Envoyer offres email" as M8
}

Marketing --> M0
Marketing --> M1
Marketing --> M2
Marketing --> M3
Marketing --> M4
Marketing --> M5
Marketing --> M6
Marketing --> M7
Marketing --> M8

M1 ..> M0 : <<include>>
M2 ..> M0 : <<include>>
M3 ..> M0 : <<include>>
M4 ..> M0 : <<include>>
M5 ..> M0 : <<include>>
M6 ..> M0 : <<include>>
M7 ..> M0 : <<include>>
M8 ..> M0 : <<include>>

M4 ..> M3 : <<extend>>
M5 ..> M3 : <<extend>>
M6 ..> M3 : <<extend>>
M7 ..> M3 : <<extend>>
@enduml
