@startuml
skinparam monochrome true
skinparam shadowing false
autonumber

actor "Réceptionniste" as recep
boundary "Vue" as vue
control "Contrôleur" as ctrl
entity "Modèle" as model

== Arrivée du client (Check-in) ==
recep -> vue : Valide l'arrivée du client
activate vue
vue -> ctrl : Transmet l'information d'arrivée
activate ctrl
ctrl -> ctrl : Vérifie que l'employé est autorisé
ctrl -> model : Change le statut de la chambre (Occupée)
activate model
model --> ctrl : Confirme la mise à jour
deactivate model
ctrl --> vue : Confirme l'enregistrement
deactivate ctrl
vue --> recep : Affiche le succès
deactivate vue

|||
== Départ du client (Check-out) ==
recep -> vue : Valide le départ du client
activate vue
vue -> ctrl : Transmet l'information de départ
activate ctrl
ctrl -> ctrl : Vérifie que l'employé est autorisé
ctrl -> model : Change le statut (Chambre à nettoyer)
activate model
model --> ctrl : Confirme la mise à jour
deactivate model
ctrl -> ctrl : Prépare la facture du séjour
ctrl --> vue : Confirme le départ et donne la facture
deactivate ctrl
vue --> recep : Affiche le succès et imprime la facture
deactivate vue
@enduml